name: "Upload Invalids Alternate UI Sound"

on:
  push:
    branches:
      - main
    paths:
      - "Invalids Alternate UI Sound/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: 3125206981
          path: "Invalids Alternate UI Sound"
          changelog: ${{ github.event.head_commit.message }}              
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
